CREATE TABLE IF NOT EXISTS settings_groups (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    machine_name VARCHAR(191) NOT NULL UNIQUE,
    label VARCHAR(191) NOT NULL,
    description VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
